// client-weather-angular/src/app/app.component.ts
import { Component, OnInit } from '@angular/core';
//import { Weather } from './models/weather';
import { GetWeatherService } from './services/get-weather.service';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent implements OnInit {  
  weather:any;
  temp:string;
  pressure:number;
  humidity:number;
  wind_speed:number;
  wind_dec:number;
  city:string;
  activeId:string = "Misto Kyyiv";
  icon:any = "10d"; 
  status:string;
  description:string;
  clouds:number;

  constructor(private getWeatherService:GetWeatherService) {}

  ngOnInit() {    
    this.getWeatherService.getWeather("Misto Kyyiv").subscribe((data:any) => {
      this.weather = data;
      this.temp = (data.main.temp - 273.15).toFixed(2);
      this.pressure = data.main.pressure;
      this.humidity = data.main.humidity;
      this.wind_speed = data.wind.speed;
      this.wind_dec = data.wind.deg;
      this.city = data.name;
      this.icon = data.weather[0].icon;
      this.status = data.weather[0].main;
      this.description = data.weather[0].description;
      this.clouds = data.clouds.all;
      //console.log(this.weather);      
      //console.log(this.icon);
    });
  }

  getCurrentWeather(city:string) {
    this.getWeatherService.getWeather(city).subscribe((data:any) => {
      this.weather = data;
      this.temp = (data.main.temp -273.15).toFixed(2);
      this.pressure = data.main.pressure;
      this.humidity = data.main.humidity;
      this.wind_speed = data.wind.speed;
      this.wind_dec = data.wind.deg;
      this.city = data.name;
      this.icon = data.weather[0].icon;
      this.status = data.weather[0].main;
      this.description = data.weather[0].description;
      this.clouds = data.clouds.all;
      //console.log(this.weather);     
      //console.log(this.icon);
    });
  }

  getActiveClass(id:string) {
    if (id === this.activeId) {
      return "btn btn-secondary active";
    } else {
      return "btn btn-secondary";
    }
  }
  
}

<div id="app">
  <div class="container">
    <p>Api info:</p>
    <ul>
      <li>Docs:
        <a href="https://openweathermap.org/current" target="_blank">https://openweathermap.org/current</a>
      </li>
      <li>Api key:
        <span class="text-primary">c2dcf8ffb5cdc3f8977bfd2ae7ea4738</span>
      </li>
    </ul>
    <hr>      
  </div>
  
  <div class="container">
    <h1>Weather App</h1>
    <h5>Angular framework was used</h5>         
    <div class="btn-group" role="group">
      <button type="button" [ngClass]="getActiveClass('Misto Kyyiv')" (click)="getCurrentWeather('Misto Kyyiv'); activeId = 'Misto Kyyiv'">Kyiv</button>
      <button type="button" [ngClass]="getActiveClass('Lutsk')" (click)="getCurrentWeather('Lutsk'); activeId = 'Lutsk'">Lutsk</button>
      <button type="button" [ngClass]="getActiveClass('London')" (click)="getCurrentWeather('London'); activeId = 'London'">London</button>
      <button type="button" [ngClass]="getActiveClass('New York')" (click)="getCurrentWeather('New York'); activeId = 'New York'">New York</button>            
    </div>
    <table class="table">
      <thead class="thead-light">
        <tr>
          <th scope="col">{{ this.city }}</th> 
          <th><img id="wicon" src="http://openweathermap.org/img/wn/{{this.icon}}.png" alt="Weather icon" /></th>          
        </tr>
      </thead>
      <tbody>
        <tr>
          <th scope="row">Current status</th>
          <td>{{ this.status }}</td>         
        </tr>
        <tr>
          <th scope="row">Detailed status</th>
          <td>{{ this.description }}</td>         
        </tr>
        <tr>
          <th scope="row">Cloudiness</th>
          <td>{{ this.clouds }} %</td>         
        </tr>
        <tr>
          <th scope="row">Temperature</th>
          <td>{{ this.temp }} °C</td>         
        </tr>
        <tr>
          <th scope="row">Atmospheric pressure</th>
          <td>{{ this.pressure }} hPa</td>         
        </tr>
        <tr>
          <th scope="row">Humidity</th>
          <td>{{ this.humidity }} %</td>          
        </tr>
        <tr>
          <th scope="row">Wind speed</th>
          <td>{{ this.wind_speed }} m/s</td>          
        </tr>
        <tr>
          <th scope="row">Wind direction</th>
          <td>{{ this.wind_dec }} °</td>          
        </tr>
      </tbody>
    </table>      
  </div>  
</div>

// client-weather-react/src/App.js
import React from 'react';
import './App.css';
import axios from 'axios';

class App extends React.Component {

  constructor(props){
    super(props);

    this.state = {
      temp: "",
      pressure: "",
      humidity: "",
      wind_speed: "",
      wind_dec: "",
      city: "",
      activeId: "",
      icon: "10d",
      status: "",
      description: "",
      clouds: ""
    }

    this.getWeather = this.getWeather.bind(this);   

  }

  componentDidMount() {
    this.getWeather("Misto Kyyiv");
    this.setState({
      activeId: "Misto Kyyiv"
    });
  }

  getWeatherKyiv(){
    this.getWeather("Misto Kyyiv");
    this.setState({
      activeId: "Misto Kyyiv"
    });
  }

   getWeatherLutsk(){
    this.getWeather("Lutsk");
    this.setState({
      activeId: "Lutsk"
    });
  }


  getWeatherLondon(){
    this.getWeather("London");
    this.setState({
      activeId: "London"
    });
  }

  getWeatherNy(){
    this.getWeather("New York");
    this.setState({
      activeId: "New York"
    });
    
  }  
  
  getWeather(city) {
    let key = "c2dcf8ffb5cdc3f8977bfd2ae7ea4738";    
    let url = "http://api.openweathermap.org/data/2.5/weather?q=" + city + "&?units=metric&APPID=" + key;
    axios
    .get("https://cors-anywhere.herokuapp.com/" + url)
    .then((response) => {
      //console.log(response.data);
      this.setState({
        temp: (response.data.main.temp - 273.15).toFixed(2),
        pressure: response.data.main.pressure,
        humidity: response.data.main.humidity,
        wind_speed: response.data.wind.speed,
        wind_dec: response.data.wind.deg,
        city: response.data.name,
        icon: response.data.weather[0].icon,
        status: response.data.weather[0].main,
        description: response.data.weather[0].description,
        clouds: response.data.clouds.all
      });      
    })
    .catch((error) => {
      console.log(error.statusText);
    });    
  } 

  render(){
    return (
      <div className="App">
        <div className="container">
          <p>Api info:</p>
          <ul>
            <li>Docs:
              <a href="https://openweathermap.org/current" rel="noopener noreferrer" target="_blank"> https://openweathermap.org/current</a>
            </li>
            <li>Api key:
              <span className="text-primary"> c2dcf8ffb5cdc3f8977bfd2ae7ea4738</span>
            </li>
          </ul>
          <hr />      
        </div>

        <div className="container">
      <h1>Weather App</h1>
      <h5>React.js framework was used</h5>        
      <div className="btn-group" role="group">
        <button type="button" className={this.state.activeId === 'Misto Kyyiv' ? 'btn btn-secondary active' : 'btn btn-secondary'} onClick={ this.getWeatherKyiv.bind(this) }>Kyiv</button>
        <button type="button" className={this.state.activeId === 'Lutsk' ? 'btn btn-secondary active' : 'btn btn-secondary'} onClick={ this.getWeatherLutsk.bind(this) }>Lutsk</button>
        <button type="button" className={this.state.activeId === 'London' ? 'btn btn-secondary active' : 'btn btn-secondary'} onClick={ this.getWeatherLondon.bind(this) }>London</button>
        <button type="button" className={this.state.activeId === 'New York' ? 'btn btn-secondary active' : 'btn btn-secondary'} onClick={ this.getWeatherNy.bind(this) }>New York</button>
      </div>
      <table className="table">
        <thead className="thead-light">
          <tr>
            <th scope="col">{ this.state.city }</th> 
            <th><img id="wicon" src={`http://openweathermap.org/img/wn/${this.state.icon}.png`} alt="Weather icon" /></th>          
          </tr>
        </thead>
        <tbody>
        <tr>
          <th scope="row">Current status</th>
            <td>{ this.state.status }</td>         
          </tr>
          <tr>
            <th scope="row">Detailed status</th>
            <td>{ this.state.description }</td>         
          </tr>
          <tr>
            <th scope="row">Cloudiness</th>
            <td>{ this.state.clouds } %</td>         
          </tr>
          <tr>
            <th scope="row">Temperature</th>
            <td>{ this.state.temp } °C</td>         
          </tr>
          <tr>
            <th scope="row">Atmospheric pressure</th>
            <td>{ this.state.pressure } hPa</td>         
          </tr>
          <tr>
            <th scope="row">Humidity</th>
            <td>{ this.state.humidity } %</td>          
          </tr>
          <tr>
            <th scope="row">Wind speed</th>
            <td>{ this.state.wind_speed } m/s</td>          
          </tr>
          <tr>
            <th scope="row">Wind direction</th>
            <td>{ this.state.wind_dec } °</td>          
          </tr>
        </tbody>
      </table>      
    </div>

      </div>
    )   
  }
}

export default App;
